"""Add primary_google_email to User model

Revision ID: 41e2581e6133
Revises: 0b2b038f2a07
Create Date: 2023-11-19 13:42:30.190813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e2581e6133'
down_revision = '0b2b038f2a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_google_email', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['primary_google_email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('primary_google_email')

    # ### end Alembic commands ###
