"""made primary google non-unique to allow for dual sign-in

Revision ID: 984c5cc25bec
Revises: 41e2581e6133
Create Date: 2023-11-19 14:56:29.538518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984c5cc25bec'
down_revision = '41e2581e6133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_primary_google_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_primary_google_email_key', ['primary_google_email'])

    # ### end Alembic commands ###
